name: Stainless — Build SDK specification
description: Create a new SDK build, either on a preview branch or on the main branch
branding:
  icon: book-open
  color: green
runs:
  using: node20
  main: dist/index.js
inputs:
  stainless_api_key:
    description: "Stainless API key."
    required: true
  oas_path:
    description: "Path to the OpenAPI file."
    required: false
  config_path:
    description: "Path to the Stainless config file."
    required: false
  project_name:
    description: "Stainless project name."
    required: true
  commit_message:
    description: "Commit message to use in the commits in the SDK repo."
    required: false
  branch:
    description: "Branch to create the build on."
    required: false
  merge_branch:
    description: "Branch that this build is merging in changes from."
    required: false
  parent_revision:
    description: >-
      JSON-stringified array of parent revisions. Each entry in the array must
      be either a commit hash, or an object with keys as file names and values
      as md5 hashes. The first matching revision that has a build will be the
      build that this build is pushed onto.
    required: false
