name: Stainless — Build SDK specification
description: Create a new SDK build, either on a preview branch or on the main branch
branding:
  icon: book-open
  color: green
runs:
  using: node20
  main: dist/index.js
inputs:
  stainless_api_key:
    description: "Stainless API key."
    required: true
  oas_path:
    description: "Path to the OpenAPI file."
    required: true
  config_path:
    description: "Path to the Stainless config file."
    required: false
  project_name:
    description: "Stainless project name."
    required: true
  commit_message:
    description: "Commit message to use in the commits in the SDK repo."
    required: false
  guess_config:
    description: "If true, renegerate the endpoints in the Stainless config file."
    required: false
  branch:
    description: "Branch to create the build on."
    required: false
  merge_branch:
    description: "Branch that this build is merging in changes from."
    required: false
  parent_oas_hash:
    description: "The md5 hash of the OpenAPI file used to create the parent build."
    required: false
  parent_config_hash:
    description: "The md5 hash of the Stainless config file used to create the parent build."
    required: false
  parent_branch:
    description: "The branch that the parent build was created on."
    required: false

