name: build

on: push

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          cache: 'pnpm'
          node-version: '22'
      - name: Install dependencies
        run: pnpm install
      - name: Build TypeScript
        run: pnpm run build
