name: build

on: push

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22'
      - name: Install pnpm
        run: npm install -g pnpm
      - name: Install dependencies
        run: pnpm install
      - name: Build TypeScript
        run: pnpm run build
      - name: Commit and push changes
        if: ${{ github.ref == 'refs/heads/main' }}
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add dist/index.js
          if git diff-index --quiet HEAD; then
            echo "No changes to commit."
          else
            git commit -m "Build: Update dist/index.js [skip ci]"
            git push
          fi
